### PR TITLE
Add IPLD README Template

### PR DESCRIPTION
**Pull request by RichardLitt**
@kumavis raised a point in https://github.com/ipld/js-ipld-eth-block/issues/1#issuecomment-264957880 that there
ought to be a template for the standard README. While there are example templates in standard-readme,
it would be better if we didn't mix standard-readme up with other templates specific to Protocol Labs.

So, I have added a folder here, and added the initial template for IPLD repositories here. We can use this to
intelligently create IPLD READMEs without wondering what belongs in each README. It would be good to have an
automatic README generator where you can choose an organizational option, and then to add READMEs for IPFS,
libp2p, and multiformats - but that is down the road, and I think that this is a good first step.

### CODE REVIEW

**Comment by RichardLitt** [comment]
@lgierth Review? Or @hsanjuan

**Comment by hsanjuan** [comment]
wanna add the standard-readme badge?

In go-* projects, godoc badge, travis and coverage badge are a plus. I don't know about JS, but travis at least is probably cross-board.

**Comment by hsanjuan** [comment]
(these are just suggestions), LGTM otherwise!

**Comment by RichardLitt** [comment]
> In go-* projects, godoc badge, travis and coverage badge are a plus. I don't know about JS, but travis at least is probably cross-board.

Been working on a remark plugin to automatically add this today. I think it is a good idea to automatically check the language and add these; I want to see if I can do this with a tool as opposed to manually doing it (like I am doing elsewhere). 

Happy to add the standard-readme badge, too.

**Pull request closed without merging**
